### PR TITLE
feat: Beamsmasher Calculator

### PR DESCRIPTION
**Pull request by mo9a7i**
Similar to: https://beamsmasher-calculator.fr/
Credits added in comments, you can move it anywhere else if you'd like. No licensing was found on original site.

### CODE REVIEW

**Comment by carlssonemil** [comment]
Cool! I think I'd rather link to the original site rather than copying it, to give the original creator credit and page views. There are other external tools that might be useful to link to, like [DECLASSIFIED](https://declassified.app/), so maybe we should add a page where we link to these tools and a description for them? 🤔

**Comment by mo9a7i** [comment]
> Cool! I think I'd rather link to the original site rather than copying it, to give the original creator credit and page views. There are other external tools that might be useful to link to, like [DECLASSIFIED](https://declassified.app/), so maybe we should add a page where we link to these tools and a description for them? 🤔

Agree,

I have adjusted the commit. Not the best design but a starting point.

**Comment by mo9a7i** [comment]
ok, I just noticed you already did that better than what I proposed.
I will close this PR.

**Comment by carlssonemil** [comment]
> ok, I just noticed you already did that better than what I proposed. I will close this PR.

Yeah sorry, forgot to write here, I added it just an hour ago! Thanks for the idea though! 🫶

**Pull request closed without merging**
